const crypto = require('crypto');
const { findLeadById, updateLeadById, readLeads } = require('./tenantLeadsStore');
const { phoneSearchVariants } = require('./phone');

function clean(value){return String(value||'').trim();}
function safeTable(value,fallback){const v=clean(value);return /^[a-zA-Z0-9_]+$/.test(v)?v:fallback;}
function secretEquals(a,b){const x=Buffer.from(String(a||'')),y=Buffer.from(String(b||''));return x.length>0&&x.length===y.length&&crypto.timingSafeEqual(x,y);}
function cfg(){return {key:clean(process.env.BOBCRM_REVERSE_INTEGRATION_KEY),requireMysql:!['0','false','no'].includes(clean(process.env.BOBCRM_REVERSE_SYNC_REQUIRE_MYSQL||'1').toLowerCase()),table:safeTable(process.env.BOBCRM_REVERSE_SYNC_EVENTS_TABLE,'zape_bobcrm_sync_events'),host:clean(process.env.EXTERNAL_CRM_MYSQL_HOST||process.env.MYSQL_HOST||'127.0.0.1'),port:Number(process.env.EXTERNAL_CRM_MYSQL_PORT||process.env.MYSQL_PORT||3306),user:clean(process.env.EXTERNAL_CRM_MYSQL_USER||process.env.MYSQL_USER),password:String(process.env.EXTERNAL_CRM_MYSQL_PASSWORD||process.env.MYSQL_PASSWORD||''),database:clean(process.env.EXTERNAL_CRM_MYSQL_DATABASE||process.env.MYSQL_DATABASE),ssl:clean(process.env.EXTERNAL_CRM_MYSQL_SSL||'').toLowerCase()};}
let pool=null,initializing=null;
async function initialize(){if(pool)return pool;if(initializing)return initializing;initializing=(async()=>{const c=cfg();if(!c.user||!c.database)throw Object.assign(new Error('Banco da sincronização reversa não configurado.'),{code:'BOBCRM_REVERSE_SYNC_DB_NOT_CONFIGURED'});const mysql=require('mysql2/promise');pool=mysql.createPool({host:c.host,port:c.port,user:c.user,password:c.password,database:c.database,connectionLimit:3,connectTimeout:10000,timezone:'Z',ssl:c.ssl==='require'?{rejectUnauthorized:false}:undefined});await pool.query('SELECT 1');await pool.query(`CREATE TABLE IF NOT EXISTS \`${c.table}\` (
 id CHAR(36) NOT NULL PRIMARY KEY,event_key VARCHAR(255) NOT NULL,event_type VARCHAR(120) NOT NULL DEFAULT '',tenant_id VARCHAR(120) NOT NULL DEFAULT '',zape_lead_id VARCHAR(120) NOT NULL DEFAULT '',bobcrm_lead_id VARCHAR(64) NOT NULL DEFAULT '',entity_version BIGINT UNSIGNED NOT NULL DEFAULT 0,status VARCHAR(32) NOT NULL DEFAULT 'processing',response_json JSON NULL,created_at DATETIME(3) NOT NULL,updated_at DATETIME(3) NOT NULL,UNIQUE KEY uq_bobcrm_sync_event(event_key),INDEX idx_bobcrm_sync_lead(tenant_id,zape_lead_id,entity_version),INDEX idx_bobcrm_sync_created(created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);return pool;})().catch(err=>{pool=null;throw err;}).finally(()=>{initializing=null;});return initializing;}
function authorize(req){const c=cfg();const header=String(req.headers.authorization||'');const token=header.startsWith('Bearer ')?header.slice(7).trim():'';return Boolean(c.key&&secretEquals(token,c.key));}
function normalizeEvent(body={}){const data=body.data&&typeof body.data==='object'?body.data:{};const event={eventKey:clean(body.eventKey).slice(0,255),eventType:clean(body.eventType||'crm.lead.snapshot').slice(0,120),leadId:clean(body.leadId||data.leadId).slice(0,64),zapeLeadId:clean(body.zapeLeadId||data.zapeLeadId).slice(0,120),tenantId:clean(body.tenantId).toLowerCase().slice(0,120),occurredAt:clean(body.occurredAt||data.updatedAt||new Date().toISOString()).slice(0,40),entityVersion:Math.max(0,Number(body.entityVersion||0)),data};if(!event.eventKey||!event.tenantId||!event.leadId)throw Object.assign(new Error('eventKey, tenantId e leadId são obrigatórios.'),{statusCode:422});if(event.eventType!=='crm.lead.snapshot')throw Object.assign(new Error('Tipo de evento não suportado.'),{statusCode:422});return event;}
function digits(value){return String(value||'').replace(/\D/g,'').replace(/^0+/,'');}
function findLocalLead(event){if(event.zapeLeadId){const direct=findLeadById(event.tenantId,event.zapeLeadId);if(direct)return direct;}const wanted=new Set(phoneSearchVariants(event.data.phone||'').map(digits));return readLeads(event.tenantId).find(lead=>{const candidates=[lead.whatsapp_digits,lead.whatsapp_raw,lead.whatsapp,lead.phone].flatMap(phoneSearchVariants).map(digits);return candidates.some(v=>wanted.has(v));})||null;}
async function applyBobCrmEvent(body){const event=normalizeEvent(body),c=cfg();let db=null;try{db=await initialize();}catch(error){if(c.requireMysql)throw error;}
 if(db){const [existing]=await db.query(`SELECT response_json FROM \`${c.table}\` WHERE event_key=? LIMIT 1`,[event.eventKey]);if(existing[0])return {...(typeof existing[0].response_json==='object'?existing[0].response_json:JSON.parse(existing[0].response_json||'{}')),idempotentReplay:true};const [versions]=await db.query(`SELECT MAX(entity_version) version FROM \`${c.table}\` WHERE tenant_id=? AND ((?<>'' AND zape_lead_id=?) OR bobcrm_lead_id=?) AND status='completed'`,[event.tenantId,event.zapeLeadId,event.zapeLeadId,event.leadId]);if(Number(versions[0]?.version||0)>event.entityVersion)return {ok:true,ignored:true,reason:'older_version',entityVersion:event.entityVersion};await db.query(`INSERT INTO \`${c.table}\` (id,event_key,event_type,tenant_id,zape_lead_id,bobcrm_lead_id,entity_version,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,'processing',NOW(3),NOW(3))`,[crypto.randomUUID(),event.eventKey,event.eventType,event.tenantId,event.zapeLeadId,event.leadId,event.entityVersion]);}
 const local=findLocalLead(event);if(!local){const error=Object.assign(new Error('Lead local do Zape não encontrado para aplicar o contexto do BobCRM.'),{statusCode:404,code:'ZAPE_LOCAL_LEAD_NOT_FOUND'});if(db)await db.query(`UPDATE \`${c.table}\` SET status='failed',response_json=?,updated_at=NOW(3) WHERE event_key=?`,[JSON.stringify({ok:false,error:error.message,code:error.code}),event.eventKey]);throw error;}
 const context={leadId:event.leadId,zapeLeadId:String(local.id||event.zapeLeadId),responsibleUserId:clean(event.data.responsibleUserId),responsible:clean(event.data.responsible),pipelineId:clean(event.data.pipelineId),pipelineName:clean(event.data.pipelineName),stageId:clean(event.data.stageId),stageName:clean(event.data.stageName),semanticStage:clean(event.data.semanticStage),status:clean(event.data.status),isLost:Boolean(event.data.isLost),temperature:clean(event.data.temperature),priority:clean(event.data.priority),tags:Array.isArray(event.data.tags)?event.data.tags:[],expectedValue:Number(event.data.expectedValue||0),closedValue:Number(event.data.closedValue||0),wonAt:clean(event.data.wonAt),lostAt:clean(event.data.lostAt),updatedAt:clean(event.data.updatedAt||event.occurredAt),entityVersion:event.entityVersion,bobcrmUrl:clean(event.data.bobcrmUrl),syncedAt:new Date().toISOString()};
 updateLeadById(event.tenantId,local.id,(lead)=>({...lead,bobcrmLeadId:event.leadId,crmContext:context,crmSyncedAt:context.syncedAt,updatedAt:lead.updatedAt||lead.createdAt||context.syncedAt}));const response={ok:true,action:'crm_context_updated',tenantId:event.tenantId,zapeLeadId:String(local.id),leadId:event.leadId,entityVersion:event.entityVersion};if(db)await db.query(`UPDATE \`${c.table}\` SET status='completed',response_json=?,updated_at=NOW(3) WHERE event_key=?`,[JSON.stringify(response),event.eventKey]);return response;}
async function status(){const c=cfg();let connected=false,error='',counts={total:0,completed:0,failed:0};try{const db=await initialize();connected=true;const [rows]=await db.query(`SELECT COUNT(*) total,SUM(status='completed') completed,SUM(status='failed') failed FROM \`${c.table}\``);counts={total:Number(rows[0]?.total||0),completed:Number(rows[0]?.completed||0),failed:Number(rows[0]?.failed||0)};}catch(e){error=String(e.message||e);}return {configured:Boolean(c.key),mysqlConnected:connected,error,counts};}
module.exports={authorizeBobCrmReverseSync:authorize,applyBobCrmEvent,initializeBobCrmReverseSync:initialize,getBobCrmReverseSyncStatus:status};
